### ISSUE TITLE
Proposal : Add programming problem in Python

### ISSUE THREAD

**Issue by kwunhang** [DevAffan/AffiCodes-Hacktoberfest2024#168]
I would like to add 2 programming problems in Python.

1. 3Sum Closest
Description: 
Given an integer array "nums" and an integer target, find three integers in "nums" such that the sum is closest to target.

2. Find K Closest Elements
Description: 
Given a sorted integer array "arr", two integers "k" and "x", return the "k" closest integers to "x" in the array in ascending order.

**Comment by Sofiyan-coder** [comment]
Hi @kwunhang  , could you please assign this issue to me? I'd love to contribute and start my open source journey with this project!

**Comment by DevAffan** [comment]
Hi @kwunhang, I've assigned this to you.

Before proceeding, please ensure that the issues you've mentioned are not already addressed in the repository. If you find that these issues are already fixed, please consider enhancing or modifying them rather than resubmitting the same algorithms.

Thank you!

**Comment by DevAffan** [comment]
Hi @Sofiyan-coder ,

Glade see your interest in my repository. Please go ahead and look at the repository and see what code you can add or modify and open a new issue, I will assign that to you. or you can directly push code to my repository and open a pull request, so I can review and accept that for you.

thank you and all the best.
