### ISSUE TITLE
excluded issue

### ISSUE THREAD

**Issue by rahul-chakradhari** [DevAffan/AffiCodes-Hacktoberfest2024#253]
i have been excluded from this but had submitted pull request but why ??

**Comment by DevAffan** [comment]
Hi @rahul-chakradhari,

I'm sorry for the inconvenience.

It seems that someone reported my repository, or Hacktoberfest has excluded it due to several DSA (Data Structure & Algorithm) pull requests that included some copied algorithms. As a result, new pull requests have been excluded.

Please avoid adding any new pull requests.
